### ISSUE TITLE
Issue resolving correct Schema ID

### ISSUE THREAD

**Issue by anjo-swe** [revpoint/logstash-codec-avro_schema_registry#8]
Kafka: 0.10.0.1
Logstash: 5.6
Plugin version: 0.9.0

`magic_byte, schema_id = datum.read(5).unpack("cI>")` gives me wrong `schema_id`, have anyone been able to resolve that issue before?

I could see that Elastic forums that it has happened before but the thread had no answers: https://discuss.elastic.co/t/kakfa-is-reading-off-the-wrong-schema-id/53298

**Comment by anjo-swe** [comment]
Think i figured it out, needed to add `key_deserializer_class` & `value_deserializer_class`

If that makes sense, should we add that to the documentation?

```
input {
  kafka {
    bootstrap_servers => "kafka.service.consul:9092"
    topics => "***"
    group_id => "***"
    auto_offset_reset => "latest"
    consumer_threads => 1
    key_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"
    value_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"
    codec => avro_schema_registry {
      endpoint => "http://schema-registry.service.consul:8081"
      username => "***"
      password => "***"
    }
  }
}
```

**Comment by sleighzy** [comment]
I also had the same issue. It appears that this documentation did exist within the file but was removed when base64encoding/decoding was introduced. I initially reverted this to it's original state in my local environment to remove the base64encoding as it breaks the Kafka Connect and Kafka Streams frameworks as they expect the data to be in Avro format within the topic. The magic byte is unable to be located if the data is base64encoded as this is not decoded first.

It looks like this issue was resolved a few days ago, see https://github.com/revpoint/logstash-codec-avro_schema_registry/commit/c73b17dd22df0fe527dd9294b0f513e51fcbc784. This change has been applied to the encoding of data prior to sending it, but has not been applied to decoding the data when consuming it.

I agree that the documentation from the original commits regarding the serializer/deserializer config for the Kafka input/output plugin be re-introduced again. Note the differences between variable names and the serialization classes as these were incorrect in the original documentation as well.

```
output {
  kafka {
    ...
    value_serializer => "org.apache.kafka.common.serialization.ByteArraySerializer"
  }
}
```

```
input {
  kafka {
    ...
    value_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"
  }
}
```

**Edit:** My above comments are based purely on the integration with the Confluent Schema Registry and the encoding of the magic byte, schema id, and data. This may not apply to all use cases outside of that scenario.

**Comment by cgiraldo** [comment]
Hi, 
The "base64" encoding is also a problem in our deployment (Confluent Platform/ kafka streams).

To solve this, we added a boolean configuration option "binary_encoded" in our last accepted pull request  #9: 

- binary_encoded:  If set to true, the output is a Java ByteArray. 

The kafka output plugin serializer should be configured accordingly as: 
 - value_serializer:  "org.apache.kafka.common.serialization.ByteArraySerializer"

I agree that the documentation should be updated to include this option for confluent platform users.

**Comment by ryananguiano** [comment]
I just updated the README after merging the latest changes. 

@anjo-swe for decoding, the deserializer issue should be solved now that we are properly importing base64.

@cgiraldo let me ask you this, since Kafka is always the output for this encoder, does it make sense that ``binary_encoded`` should be true by default? Or is this a special case that you need it for?

**Comment by ryananguiano** [comment]
@anjo-swe Nevermind, the deserializer should always be passed and is updated in the README

**Comment by anjo-swe** [comment]
Thanks!

**Comment by cgiraldo** [comment]
@ryananguiano . IMHO avro encoding should be  `binary_encoded` by default. Base64 encoding is ok if you transmit binary data using a text-based protocol such as HTTP, but this is not the case with kafka protocol. The only downside is that the default serializer of kafka output plugin is StringSerializer and should be changed to ByteArraySerializer if `binary_encoded`.

**Comment by ryananguiano** [comment]
@cgiraldo ok. I agree. I will update the defaults and note this in the docs.
